### ISSUE TITLE
Reboot avec ctrl+alt+supp

### ISSUE THREAD

**Issue by berlius** [NuTyX/current#1]
***extra/base-extra/sysvinit/***

Dans le fichier ***inittab*** le paramètre ***-h*** a été passé à **shutdown**  pour la combinaison de touche **ctrlaltdel**. Le système "**halt**" donc au lieu de faire un "**reboot**". C'est le paramètre ***-r*** qu'il faut lui passer. Voici le patch : 

--- Pkgfile	2015-11-03 23:47:22.000000000 +0100
+++ Pkgfile1	2015-11-03 23:47:54.000000000 +0100
@@ -42,7 +42,7 @@
 l5:5:wait:/etc/rc.d/init.d/rc 5
 l6:6:wait:/etc/rc.d/init.d/rc 6
 
\-ca:12345:ctrlaltdel:/sbin/shutdown -t1 -a -h now
\+ca:12345:ctrlaltdel:/sbin/shutdown -t1 -a -r now
 
 su:S016:once:/sbin/sulogin

**Comment by tnut** [comment]
C'est une volonté de ma part. Sous NuTyX ctrl+alt+supp arrête la machine depuis la première version de NuTyX (2007)

**Comment by tnut** [comment]
J'ai retrouvé le port de la 2008 (ok c'est la 2ième version, celui de la première est j'ai bien peur perdu à jamais)
http://downloads.nutyx.org/ports/2008/base/aaabasicfs/inittab

**Comment by berlius** [comment]
ah bien merci pour l'info
