### ISSUE TITLE
Pas de sons système Mate 1.12

### ISSUE THREAD

**Issue by sh4d0w31410** [NuTyX/current#3]
Je n'arrive pas à activer les sons systèmes avec  Mate.
Le son en général marche (youtube, vidéos, musique), mais il manque quelque chose pour les sons systèmes.
Dans le menu Système > Centre de contrôle > Son, tout l'onglet "effets sonores" est grisé.
Si j'installe gnome et gnome-extra, que je relance une session mate, les sons systèmes fonctionnent.
Je n'arrive pas à trouver le(s) paquet(s) manquant(s) dans mate par rapport a gnome pour résoudre ce problème.

**Comment by tnut** [comment]
Hmm vais voir ça

**Comment by tnut** [comment]
rien à voir avec cette collection à vrai dire
