### ISSUE TITLE
wrong hostname

### ISSUE THREAD

**Issue by guy2009** [NuTyX/current#4]
Salut,

Chez moi, le hostname indiqué dans le fichier /etc/sysconfig/network n'est pas pris en compte.
Pour résoudre ce problème, j'ai du ajouter
<code>hostname $HOSTNAME</code>
à la fin de ce ficher

Guy

**Comment by tnut** [comment]
C est corrigé sur houaphan il me semble

**Comment by guy2009** [comment]
Oui, c'est juste, je vois que c'est corrigé dans le git, mais pas encore dans le paquet binaire.
Encore un peu de patience !

Bàt
